server {
    listen 80;
    server_name clinica-grupoN.lab.umng.edu.co;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name clinica-grupoN.lab.umng.edu.co;

    ssl_certificate     /etc/letsencrypt/live/clinica-grupoN.lab.umng.edu.co/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/clinica-grupoN.lab.umng.edu.co/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    # Headers de seguridad - Punto 3.1 del parcial
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'; font-src 'self'; connect-src 'self' http://10.0.0.11:8000; frame-ancestors 'none';" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), camera=(), microphone=()" always;

    root /var/www/clinica/dist/clinica-frontend;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://10.0.0.11:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
